### ISSUE TITLE
Not usable due to missing install procedures

### ISSUE THREAD

**Issue by rolsman1974** [jeremyherbert/mcp2210-python#7]
I keep on running into the following error message, I've tried many things to install but unfortunately noting that solved the following issue. I am using a Mac and Visual Code to get this repository working.

ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

As said tried to install many usb related packages, used Google to do some research on this error message but did din't help me.
It's true that I'm not that experienced with python, however to my opinion with a good setup / installation instruction for people new to python should resolve issues like the error message above.

It would be nice if the repository could be updated with better instructions how and what to install in order to run the code.

Kind regards,
Raymond

**Comment by jeremyherbert** [comment]
Hi Raymond,

This code is published under a “hope it works for you” kind of license because basically, I have no time to support it and I don’t have any hardware to test with anymore. 

With that said, the readme is correct - you just run the pip install command and then it should “just work” (because this command installs all of the necessary dependencies, there is nothing more to install). It looks like in your case the hidapi library install broke or is broken: https://github.com/trezor/cython-hidapi

I’m afraid I’m not familiar with vscode and how it sets up its python environment, and I also am not too familiar with the inner workings of this failing library, so I’m afraid I can’t really help you much further.
